1. Numpy: type, dtype, shape, dimension, size

In [1]:
# Numpy는 항상 별도의 라이브러리로 존재(import 필요)
# Numpy는 배열에서 하나의 데이터 타입만 가질 수 있다.

import numpy as np
# as np(임의)는 불러올 라이브러리의 별명을 할당하는 것
a = np.array([7, 8, 9, 10, 11])
# array에서는 모든 요소가 같은 크기의 공간을 차지한다. 구분은 공백으로.
print(f'{a}\n{"object type:":>12} {type(a)}\n{"data type:":>12} {a.dtype}\n{"shape:":>12} \
{a.shape}\n{"demension:":>12} {a.ndim}\n{"array size:":>12} {a.size}')
a1 = np.array([a]); print(a1.shape); print(a1)

[ 7  8  9 10 11]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (5,)
  demension: 1
 array size: 5
(1, 5)
[[ 7  8  9 10 11]]


In [12]:
b = np.array([[1.0, 2, 3, 4, 5], [8, 9, 10, 11, 12.2]])
# 12.2(float type)때문에 모든 int가 float로 통일
print(f'{b}\n{"object type:":>12} {type(b)}\n{"data type:":>12} {b.dtype}\n{"shape:":>12} \
{b.shape}\n{"dimension:":>12} {b.ndim}\n{"array size:":>12} {b.size}')

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
object type: <class 'numpy.ndarray'>
  data type: float64
      shape: (2, 5)
  dimension: 2
 array size: 10


In [4]:
c = np.array([[[1,2,3,4,5], [8,9,10,11,12]], [[4,5,6,7,8], [10,11,12,13,14]]])
print(f'{c}\n{"object type:":>12} {type(c)}\n{"data type:":>12} {c.dtype}\n{"shape:":>12} \
{c.shape}\n{"dimension:":>12} {c.ndim}\n{"array size:":>12} {c.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (2, 2, 5)
  dimension: 3
 array size: 20


In [17]:
ac1 = np.array([[[1,2,3,4,5],[8,9,10,11,12]]])
print(f'{ac1}\n{"object type:":>12} {type(ac1)}\n{"data type:":>12} {ac1.dtype}\n{"shape:":>12} \
{ac1.shape}\n{"dimension:":>12} {ac1.ndim}\n{"array size:":>12} {ac1.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (1, 2, 5)
  dimension: 3
 array size: 10


2. Numpy : special arrays and indexing

In [19]:
test = np.array([1, 2, 3, '4'])
print(test)

['1' '2' '3' '4']


In [27]:
a_zeros = np.zeros((2, 3))
# zeros는 모든 요소가 0
a_ones = np.ones((2, 4), dtype=int)
# 모든 요소가 1
print(a_ones)
a_full = np.full((2, 5), 7)
# 요소의 값을 지정할 수 있는 함수(여기서는 7)
print(a_full, a_full.size)
print(np.eye(3))
# n by n matrix를 출력하는 함수

[[1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]] 10
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
a_ran = np.random.random((2,3,4))
# random 라이브러리를 불러온 후 그 안의 random 함수를 사용
# 0이상 1미만
print(f'{a_ran}\n{a_ran.dtype}\n{a_ran.ndim}')

[[[0.88230121 0.0227313  0.59118782 0.76294242]
  [0.15453222 0.90161925 0.24397019 0.61064594]
  [0.60779122 0.63309523 0.711939   0.4995322 ]]

 [[0.48229471 0.13166628 0.56627998 0.45542176]
  [0.18188798 0.9312922  0.20701938 0.31299026]
  [0.1430938  0.17551749 0.89807838 0.69110577]]]
float64
3


In [33]:
print(c)
print(c[1][0][4])
print(c[1,0,4])
print(c[0][0][4])
print(c[0,0,4])
# 두 방식 모두 사용 가능

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
8
8
5
5


3. Numpy : flatting and making arrays with arrange function

In [5]:
print(c)
l = []
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n{np.array(l)}')

print(np.array(c.flat))
# flat은 n차원 array를 일차원 array로 변환(생성자의 역할까지만 수행)

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]


In [41]:
g = np.arange(21)
# list의 range와 기능 동일
print(f'{g}\n{type(g)}')
print(g.reshape(1,3,7))
# 차원 구성을 만드는 함수

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [43]:
h = np.arange(5, 21, 2)
print(h)
print(np.arange(1, 21).reshape(2, 10))

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [45]:
a_ss = np.linspace(0, 1, 11)
# 범위 내애 동일한 간격으로 지정한 요소수의 array 생성(끝 지정 수 포함)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
11


4. Numpy : array operation

In [25]:
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape, xb.shape)
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [6]:
print(np.add(xa, xb))
print(np.subtract(xa, xb))
print(np.multiply(xa, xb))
print(np.sqrt(xa))           #

[[ 4  6]
 [ 8 10]
 [12 14]]
[[-2 -2]
 [-2 -2]
 [-2 -2]]
[[ 3  8]
 [15 24]
 [35 48]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [23]:
xc = np.ones((2, 1), int)
print(xc, xc.shape, xc.ndim, xc.dtype)

[[1]
 [1]] (2, 1) 2 int32


In [26]:
print(xa.dot(xc))    # dot은 행렬곱 함수      
print(np.dot(xb,xc))

[[ 3]
 [ 7]
 [11]]
[[ 7]
 [11]
 [15]]


In [11]:
xd = np.array([[1,2],[1,2]]); print(xd)
print(np.dot(xa,xd)); print(np.dot(xb,xd))

[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


In [13]:
print(xa.T)
# T는 x by y를 y by x로 바꾸는 함수(transposing)
print(xb+3)
print(xb)

[[1 3 5]
 [2 4 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[3 4]
 [5 6]
 [7 8]]


5. Numpy : broadcasting(차원이 다른 Matrix 연산)

In [14]:
ya = np.arange(1, 10).reshape(3,3); print(ya)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
yv1 = np.array([[1],[2],[3]]);print(yv1)

[[1]
 [2]
 [3]]


In [20]:
yb = ya + yv1; print(yb)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [21]:
yv2 = np.array([[1,2,3]]); print(yv2)

[[1 2 3]]


In [4]:
yc = np.array([[3,4,5],[6,7,8],[9,10,11]])
print(yc)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


6.Numpy : Summary Statistics

In [8]:
print(yc.sum(), yc.mean(), yc.min(), yc.max(), yc.var(), yc.std())
# 모든 요소 연산
print(yc.argmax(), yc.argmin())
# 최댓값, 최솟값의 index를 알 수 있다.(차원 구분 X, 요소들을 1차원에서 인식)
print(yc.mean(axis = 0), yc.mean(axis =1))
# 0은 vertical 계산, 1은 horizontal 계산

63 7.0 3 11 6.666666666666667 2.581988897471611
8 0
[6. 7. 8.] [ 4.  7. 10.]


7. Numpy : Slicing, Flatten, and Stacking

In [10]:
karray = np.arange(21).reshape(3,7); print(karray)
print(karray[0], karray[0,:4])  # row index가 0, column index가 0:4
print(karray[:2])
print(karray[:2,:3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[0 1 2 3 4 5 6] [0 1 2 3]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[0 1 2]
 [7 8 9]]


In [13]:
karray = np.arange(21).reshape(3, 7); print(karray)
print(karray[[0,2]]) # ,를 활용하면 해당 번호에 해당하는 index만 return
print(karray[:,[1,5]])
print(karray[:,1:5])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]
[[ 1  5]
 [ 8 12]
 [15 19]]
[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [20]:
fkarray = karray.flatten()
print(fkarray, fkarray.shape)        # 1차원화(간편)
fkarray1 = np.array(karray.flat)     # np.array가 필요
print(fkarray1)
rfkarray = karray.reshape(1,21)
print(karray)
print(rfkarray, rfkarray.shape)
rfkarray.resize(3,7)                 # resize 함수는 객체를 변화시킨다
print(rfkarray, rfkarray.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (21,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]] (1, 21)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] (3, 7)


In [22]:
karray1 = karray[:,:3]; karray2 = karray[:, 3:6]
karrayh = np.hstack([karray1, karray2]); print(karrayh)  # horizontal
karrayv = np.vstack([karray1, karray2]); print(karrayv)  # vertical

[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]]
[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [ 3  4  5]
 [10 11 12]
 [17 18 19]]
